version: '3'

services:
  redis:
    container_name: proxypool-redis
    image: redis:latest
    restart: always
    networks:
      - proxypool_net

  proxypool:
    container_name: proxypool
    image: jontyding/proxypool:test
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    networks:
      - proxypool_net

networks:
  proxypool_net: