# 服务配置
[server]
port = 8080
mode = "debug"  # debug/release

# Redis配置
[redis]
host = "localhost"
port = 6379
password = ""
db = 0

# 代理验证配置
[validator]
timeout = 10  # 超时时间（秒）
check_interval = 10  # 定时检查间隔（分钟）
test_url = "http://httpbin.org/ip"

# 爬虫配置
[crawler]
interval = 30  # 爬取间隔（分钟）
batch_size = 20  # 每批验证的代理数量
fetch_delay = 2  # 每个页面爬取间隔（秒）
max_retry = 3    # 最大重试次数

# 日志配置
[log]
level = "debug"  # debug/info/warn/error
output = "file"  # console/file
file_path = "logs/proxy_pool.log"

# 安全配置
[security]
# 基本认证
auth_enabled = true  # 是否启用认证
username = "admin"   # 基本认证用户名
password = "123456"  # 基本认证密码

# API Key认证
api_key_enabled = true              # 是否启用 API Key
api_keys = ["key1", "key2", "key3"] # 允许的 API Key 列表

# 限流配置
rate_limit_enabled = true    # 是否启用限流
rate_limit = 100            # 每个时间窗口最大请求数
rate_window = 1             # 时间窗口（分钟）
ban_duration = 24           # 封禁时长（小时）
